/*
 * This file was autogenerated by RTDB Generator script
 * Date of generation: 24 May 2025 at 09:46:05
 * To modify this file run the RTDB Generator script again
 * Include this header file only in the corresponding module .cpp file to avoid multiple definitions
 */

#include "rtdb.h"
#include "crcm.h"
#include "errh.h"
#include <freertos/FreeRTOS.h>
#include <freertos/semphr.h>
#include "mdll.h"

static bool rtdb_s_moduleInit_tB = false;

static SemaphoreHandle_t db_mutex;

const char* rtdb_unitLookupTable[VAR_UNIT_MAX_NUM] =
{
    [VAR_UNIT_us] = "us",
};

tU8S* rtdb_arr_tU8S[NUM_OF_tU8S];
tU16S* rtdb_arr_tU16S[NUM_OF_tU16S];
tU32S* rtdb_arr_tU32S[NUM_OF_tU32S];
tS8S* rtdb_arr_tS8S[NUM_OF_tS8S];
tS16S* rtdb_arr_tS16S[NUM_OF_tS16S];
tS32S* rtdb_arr_tS32S[NUM_OF_tS32S];
tES* rtdb_arr_tES[NUM_OF_tES];
tBS* rtdb_arr_tBS[NUM_OF_tBS];
tF32S* rtdb_arr_tF32S[NUM_OF_tF32S];

static bool rtdb_lock(void)
{
    bool taken = xSemaphoreTake(db_mutex, pdMS_TO_TICKS(50)) == pdTRUE;
    return taken;
}

static void rtdb_unlock(void)
{
    xSemaphoreGive(db_mutex);
}

tU32 rtdb_calcCrc32_tU8S(tU8S* VarAddrs, tU32 VarSize)
{
    tU32 toReturn = 0;
    if (nullptr == VarAddrs)
    {
        errh_reportError(ERRH_ERROR_HIGH, MODULE_RTDB, 0, RTDB_API_CALC_CRC_TU8S, ERRH_ERR_ACCESS_NULL_PTR_U32);
    }
    else
    {
        tU32 offset = sizeof(VarAddrs->ss.crc32);
        toReturn = crcm_CRC32(((tU8*)VarAddrs) + offset, VarSize - offset);
    }
    return toReturn;
}

tU32 rtdb_checkCrc32_tU8S(tU8S* VarAddrs, tU32 VarSize)
{
    tU32 expectedCrc32 = rtdb_calcCrc32_tU8S(VarAddrs, VarSize);
    return VarAddrs->ss.crc32 != expectedCrc32;
}

tU32 rtdb_calcCrc32_tU16S(tU16S* VarAddrs, tU32 VarSize)
{
    tU32 toReturn = 0;
    if (nullptr == VarAddrs)
    {
        errh_reportError(ERRH_ERROR_HIGH, MODULE_RTDB, 0, RTDB_API_CALC_CRC_TU16S, ERRH_ERR_ACCESS_NULL_PTR_U32);
    }
    else
    {
        tU32 offset = sizeof(VarAddrs->ss.crc32);
        toReturn = crcm_CRC32(((tU8*)VarAddrs) + offset, VarSize - offset);
    }
    return toReturn;
}

tU32 rtdb_checkCrc32_tU16S(tU16S* VarAddrs, tU32 VarSize)
{
    tU32 expectedCrc32 = rtdb_calcCrc32_tU16S(VarAddrs, VarSize);
    return VarAddrs->ss.crc32 != expectedCrc32;
}

tU32 rtdb_calcCrc32_tU32S(tU32S* VarAddrs, tU32 VarSize)
{
    tU32 toReturn = 0;
    if (nullptr == VarAddrs)
    {
        errh_reportError(ERRH_ERROR_HIGH, MODULE_RTDB, 0, RTDB_API_CALC_CRC_TU32S, ERRH_ERR_ACCESS_NULL_PTR_U32);
    }
    else
    {
        tU32 offset = sizeof(VarAddrs->ss.crc32);
        toReturn = crcm_CRC32(((tU8*)VarAddrs) + offset, VarSize - offset);
    }
    return toReturn;
}

tU32 rtdb_checkCrc32_tU32S(tU32S* VarAddrs, tU32 VarSize)
{
    tU32 expectedCrc32 = rtdb_calcCrc32_tU32S(VarAddrs, VarSize);
    return VarAddrs->ss.crc32 != expectedCrc32;
}

tU32 rtdb_calcCrc32_tS8S(tS8S* VarAddrs, tU32 VarSize)
{
    tU32 toReturn = 0;
    if (nullptr == VarAddrs)
    {
        errh_reportError(ERRH_ERROR_HIGH, MODULE_RTDB, 0, RTDB_API_CALC_CRC_TS8S, ERRH_ERR_ACCESS_NULL_PTR_U32);
    }
    else
    {
        tU32 offset = sizeof(VarAddrs->ss.crc32);
        toReturn = crcm_CRC32(((tU8*)VarAddrs) + offset, VarSize - offset);
    }
    return toReturn;
}

tU32 rtdb_checkCrc32_tS8S(tS8S* VarAddrs, tU32 VarSize)
{
    tU32 expectedCrc32 = rtdb_calcCrc32_tS8S(VarAddrs, VarSize);
    return VarAddrs->ss.crc32 != expectedCrc32;
}

tU32 rtdb_calcCrc32_tS16S(tS16S* VarAddrs, tU32 VarSize)
{
    tU32 toReturn = 0;
    if (nullptr == VarAddrs)
    {
        errh_reportError(ERRH_ERROR_HIGH, MODULE_RTDB, 0, RTDB_API_CALC_CRC_TS16S, ERRH_ERR_ACCESS_NULL_PTR_U32);
    }
    else
    {
        tU32 offset = sizeof(VarAddrs->ss.crc32);
        toReturn = crcm_CRC32(((tU8*)VarAddrs) + offset, VarSize - offset);
    }
    return toReturn;
}

tU32 rtdb_checkCrc32_tS16S(tS16S* VarAddrs, tU32 VarSize)
{
    tU32 expectedCrc32 = rtdb_calcCrc32_tS16S(VarAddrs, VarSize);
    return VarAddrs->ss.crc32 != expectedCrc32;
}

tU32 rtdb_calcCrc32_tS32S(tS32S* VarAddrs, tU32 VarSize)
{
    tU32 toReturn = 0;
    if (nullptr == VarAddrs)
    {
        errh_reportError(ERRH_ERROR_HIGH, MODULE_RTDB, 0, RTDB_API_CALC_CRC_TS32S, ERRH_ERR_ACCESS_NULL_PTR_U32);
    }
    else
    {
        tU32 offset = sizeof(VarAddrs->ss.crc32);
        toReturn = crcm_CRC32(((tU8*)VarAddrs) + offset, VarSize - offset);
    }
    return toReturn;
}

tU32 rtdb_checkCrc32_tS32S(tS32S* VarAddrs, tU32 VarSize)
{
    tU32 expectedCrc32 = rtdb_calcCrc32_tS32S(VarAddrs, VarSize);
    return VarAddrs->ss.crc32 != expectedCrc32;
}

tU32 rtdb_calcCrc32_tES(tES* VarAddrs, tU32 VarSize)
{
    tU32 toReturn = 0;
    if (nullptr == VarAddrs)
    {
        errh_reportError(ERRH_ERROR_HIGH, MODULE_RTDB, 0, RTDB_API_CALC_CRC_TES, ERRH_ERR_ACCESS_NULL_PTR_U32);
    }
    else
    {
        tU32 offset = sizeof(VarAddrs->ss.crc32);
        toReturn = crcm_CRC32(((tU8*)VarAddrs) + offset, VarSize - offset);
    }
    return toReturn;
}

tU32 rtdb_checkCrc32_tES(tES* VarAddrs, tU32 VarSize)
{
    tU32 expectedCrc32 = rtdb_calcCrc32_tES(VarAddrs, VarSize);
    return VarAddrs->ss.crc32 != expectedCrc32;
}

tU32 rtdb_calcCrc32_tBS(tBS* VarAddrs, tU32 VarSize)
{
    tU32 toReturn = 0;
    if (nullptr == VarAddrs)
    {
        errh_reportError(ERRH_ERROR_HIGH, MODULE_RTDB, 0, RTDB_API_CALC_CRC_TBS, ERRH_ERR_ACCESS_NULL_PTR_U32);
    }
    else
    {
        tU32 offset = sizeof(VarAddrs->ss.crc32);
        toReturn = crcm_CRC32(((tU8*)VarAddrs) + offset, VarSize - offset);
    }
    return toReturn;
}

tU32 rtdb_checkCrc32_tBS(tBS* VarAddrs, tU32 VarSize)
{
    tU32 expectedCrc32 = rtdb_calcCrc32_tBS(VarAddrs, VarSize);
    return VarAddrs->ss.crc32 != expectedCrc32;
}

tU32 rtdb_calcCrc32_tF32S(tF32S* VarAddrs, tU32 VarSize)
{
    tU32 toReturn = 0;
    if (nullptr == VarAddrs)
    {
        errh_reportError(ERRH_ERROR_HIGH, MODULE_RTDB, 0, RTDB_API_CALC_CRC_TF32S, ERRH_ERR_ACCESS_NULL_PTR_U32);
    }
    else
    {
        tU32 offset = sizeof(VarAddrs->ss.crc32);
        toReturn = crcm_CRC32(((tU8*)VarAddrs) + offset, VarSize - offset);
    }
    return toReturn;
}

tU32 rtdb_checkCrc32_tF32S(tF32S* VarAddrs, tU32 VarSize)
{
    tU32 expectedCrc32 = rtdb_calcCrc32_tF32S(VarAddrs, VarSize);
    return VarAddrs->ss.crc32 != expectedCrc32;
}

void rtdb_assign_tU8S( tU8S* VarAddrs,
                         tU32 Indx,
                         unitEnumT Unit,
                         tU8 Min,
                         tU8 Def,
                         tU8 Max,
                         const char* Comment )
{
    rtdb_arr_tU8S[Indx] = VarAddrs; // Copy address of variable to lookup table
    VarAddrs->tU8_val = Def;
    VarAddrs->tU8_min = Min;
    VarAddrs->tU8_def = Def;
    VarAddrs->tU8_max = Max;
    VarAddrs->ss.signalUnit = Unit;
    VarAddrs->ss.signalCmnt = Comment;
    VarAddrs->ss.signalState = SIGNAL_OK;
    VarAddrs->ss.objectStatus = OBJECT_STANDARD;
    VarAddrs->ss.crc32 = rtdb_calcCrc32_tU8S(VarAddrs, sizeof(tU8S));
};

void rtdb_assign_tU16S( tU16S* VarAddrs,
                         tU32 Indx,
                         unitEnumT Unit,
                         tU16 Min,
                         tU16 Def,
                         tU16 Max,
                         const char* Comment )
{
    rtdb_arr_tU16S[Indx] = VarAddrs; // Copy address of variable to lookup table
    VarAddrs->tU16_val = Def;
    VarAddrs->tU16_min = Min;
    VarAddrs->tU16_def = Def;
    VarAddrs->tU16_max = Max;
    VarAddrs->ss.signalUnit = Unit;
    VarAddrs->ss.signalCmnt = Comment;
    VarAddrs->ss.signalState = SIGNAL_OK;
    VarAddrs->ss.objectStatus = OBJECT_STANDARD;
    VarAddrs->ss.crc32 = rtdb_calcCrc32_tU16S(VarAddrs, sizeof(tU16S));
};

void rtdb_assign_tU32S( tU32S* VarAddrs,
                         tU32 Indx,
                         unitEnumT Unit,
                         tU32 Min,
                         tU32 Def,
                         tU32 Max,
                         const char* Comment )
{
    rtdb_arr_tU32S[Indx] = VarAddrs; // Copy address of variable to lookup table
    VarAddrs->tU32_val = Def;
    VarAddrs->tU32_min = Min;
    VarAddrs->tU32_def = Def;
    VarAddrs->tU32_max = Max;
    VarAddrs->ss.signalUnit = Unit;
    VarAddrs->ss.signalCmnt = Comment;
    VarAddrs->ss.signalState = SIGNAL_OK;
    VarAddrs->ss.objectStatus = OBJECT_STANDARD;
    VarAddrs->ss.crc32 = rtdb_calcCrc32_tU32S(VarAddrs, sizeof(tU32S));
};

void rtdb_assign_tS8S( tS8S* VarAddrs,
                         tU32 Indx,
                         unitEnumT Unit,
                         tS8 Min,
                         tS8 Def,
                         tS8 Max,
                         const char* Comment )
{
    rtdb_arr_tS8S[Indx] = VarAddrs; // Copy address of variable to lookup table
    VarAddrs->tS8_val = Def;
    VarAddrs->tS8_min = Min;
    VarAddrs->tS8_def = Def;
    VarAddrs->tS8_max = Max;
    VarAddrs->ss.signalUnit = Unit;
    VarAddrs->ss.signalCmnt = Comment;
    VarAddrs->ss.signalState = SIGNAL_OK;
    VarAddrs->ss.objectStatus = OBJECT_STANDARD;
    VarAddrs->ss.crc32 = rtdb_calcCrc32_tS8S(VarAddrs, sizeof(tS8S));
};

void rtdb_assign_tS16S( tS16S* VarAddrs,
                         tU32 Indx,
                         unitEnumT Unit,
                         tS16 Min,
                         tS16 Def,
                         tS16 Max,
                         const char* Comment )
{
    rtdb_arr_tS16S[Indx] = VarAddrs; // Copy address of variable to lookup table
    VarAddrs->tS16_val = Def;
    VarAddrs->tS16_min = Min;
    VarAddrs->tS16_def = Def;
    VarAddrs->tS16_max = Max;
    VarAddrs->ss.signalUnit = Unit;
    VarAddrs->ss.signalCmnt = Comment;
    VarAddrs->ss.signalState = SIGNAL_OK;
    VarAddrs->ss.objectStatus = OBJECT_STANDARD;
    VarAddrs->ss.crc32 = rtdb_calcCrc32_tS16S(VarAddrs, sizeof(tS16S));
};

void rtdb_assign_tS32S( tS32S* VarAddrs,
                         tU32 Indx,
                         unitEnumT Unit,
                         tS32 Min,
                         tS32 Def,
                         tS32 Max,
                         const char* Comment )
{
    rtdb_arr_tS32S[Indx] = VarAddrs; // Copy address of variable to lookup table
    VarAddrs->tS32_val = Def;
    VarAddrs->tS32_min = Min;
    VarAddrs->tS32_def = Def;
    VarAddrs->tS32_max = Max;
    VarAddrs->ss.signalUnit = Unit;
    VarAddrs->ss.signalCmnt = Comment;
    VarAddrs->ss.signalState = SIGNAL_OK;
    VarAddrs->ss.objectStatus = OBJECT_STANDARD;
    VarAddrs->ss.crc32 = rtdb_calcCrc32_tS32S(VarAddrs, sizeof(tS32S));
};

void rtdb_assign_tES( tES* VarAddrs,
                         tU32 Indx,
                         unitEnumT Unit,
                         tE Min,
                         tE Def,
                         tE Max,
                         const char* Comment )
{
    rtdb_arr_tES[Indx] = VarAddrs; // Copy address of variable to lookup table
    VarAddrs->tE_val = Def;
    VarAddrs->tE_min = Min;
    VarAddrs->tE_def = Def;
    VarAddrs->tE_max = Max;
    VarAddrs->ss.signalUnit = Unit;
    VarAddrs->ss.signalCmnt = Comment;
    VarAddrs->ss.signalState = SIGNAL_OK;
    VarAddrs->ss.objectStatus = OBJECT_STANDARD;
    VarAddrs->ss.crc32 = rtdb_calcCrc32_tES(VarAddrs, sizeof(tES));
};

void rtdb_assign_tBS( tBS* VarAddrs,
                         tU32 Indx,
                         unitEnumT Unit,
                         tB Min,
                         tB Def,
                         tB Max,
                         const char* Comment )
{
    rtdb_arr_tBS[Indx] = VarAddrs; // Copy address of variable to lookup table
    VarAddrs->tB_val = Def;
    VarAddrs->tB_min = Min;
    VarAddrs->tB_def = Def;
    VarAddrs->tB_max = Max;
    VarAddrs->ss.signalUnit = Unit;
    VarAddrs->ss.signalCmnt = Comment;
    VarAddrs->ss.signalState = SIGNAL_OK;
    VarAddrs->ss.objectStatus = OBJECT_STANDARD;
    VarAddrs->ss.crc32 = rtdb_calcCrc32_tBS(VarAddrs, sizeof(tBS));
};

void rtdb_assign_tF32S( tF32S* VarAddrs,
                         tU32 Indx,
                         unitEnumT Unit,
                         tF32 Min,
                         tF32 Def,
                         tF32 Max,
                         const char* Comment )
{
    rtdb_arr_tF32S[Indx] = VarAddrs; // Copy address of variable to lookup table
    VarAddrs->tF32_val = Def;
    VarAddrs->tF32_min = Min;
    VarAddrs->tF32_def = Def;
    VarAddrs->tF32_max = Max;
    VarAddrs->ss.signalUnit = Unit;
    VarAddrs->ss.signalCmnt = Comment;
    VarAddrs->ss.signalState = SIGNAL_OK;
    VarAddrs->ss.objectStatus = OBJECT_STANDARD;
    VarAddrs->ss.crc32 = rtdb_calcCrc32_tF32S(VarAddrs, sizeof(tF32S));
};


tU32 rtdb_write_tU8S( tU8SEnumT VarName , tU8 NewVal)
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TU8S, RTDB_ERR_SEMAPH_TAKE_TU8S);
    }
    else
    {
        // Request out of range TODO: add error reporting
        if (NUM_OF_tU8S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TU8S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tU8S(rtdb_arr_tU8S[VarName], sizeof(tU8S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TU8S, RTDB_ERR_WRONG_CRC_TU8S);
            stsCode = 2;
        }
        // check for MIN
        else if ( NewVal < rtdb_arr_tU8S[VarName]->tU8_min)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TU8S, RTDB_ERR_VAL_BELOW_MIN_TU8S);
            stsCode = 3;
        }
        // check for MAX
        else if ( NewVal > rtdb_arr_tU8S[VarName]->tU8_max)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TU8S, RTDB_ERR_VAL_ABOVE_MAX_TU8S);
            stsCode = 4;
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tU8S[VarName]->ss.objectStatus)
            {
                rtdb_arr_tU8S[VarName]->tU8_val = NewVal;
                rtdb_arr_tU8S[VarName]->ss.signalState = SIGNAL_OK;
                rtdb_arr_tU8S[VarName]->ss.crc32 = rtdb_calcCrc32_tU8S(rtdb_arr_tU8S[VarName], sizeof(tU8S));
            }
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_write_tU16S( tU16SEnumT VarName , tU16 NewVal)
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TU16S, RTDB_ERR_SEMAPH_TAKE_TU16S);
    }
    else
    {
        // Request out of range TODO: add error reporting
        if (NUM_OF_tU16S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TU16S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tU16S(rtdb_arr_tU16S[VarName], sizeof(tU16S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TU16S, RTDB_ERR_WRONG_CRC_TU16S);
            stsCode = 2;
        }
        // check for MIN
        else if ( NewVal < rtdb_arr_tU16S[VarName]->tU16_min)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TU16S, RTDB_ERR_VAL_BELOW_MIN_TU16S);
            stsCode = 3;
        }
        // check for MAX
        else if ( NewVal > rtdb_arr_tU16S[VarName]->tU16_max)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TU16S, RTDB_ERR_VAL_ABOVE_MAX_TU16S);
            stsCode = 4;
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tU16S[VarName]->ss.objectStatus)
            {
                rtdb_arr_tU16S[VarName]->tU16_val = NewVal;
                rtdb_arr_tU16S[VarName]->ss.signalState = SIGNAL_OK;
                rtdb_arr_tU16S[VarName]->ss.crc32 = rtdb_calcCrc32_tU16S(rtdb_arr_tU16S[VarName], sizeof(tU16S));
            }
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_write_tU32S( tU32SEnumT VarName , tU32 NewVal)
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TU32S, RTDB_ERR_SEMAPH_TAKE_TU32S);
    }
    else
    {
        // Request out of range TODO: add error reporting
        if (NUM_OF_tU32S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TU32S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tU32S(rtdb_arr_tU32S[VarName], sizeof(tU32S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TU32S, RTDB_ERR_WRONG_CRC_TU32S);
            stsCode = 2;
        }
        // check for MIN
        else if ( NewVal < rtdb_arr_tU32S[VarName]->tU32_min)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TU32S, RTDB_ERR_VAL_BELOW_MIN_TU32S);
            stsCode = 3;
        }
        // check for MAX
        else if ( NewVal > rtdb_arr_tU32S[VarName]->tU32_max)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TU32S, RTDB_ERR_VAL_ABOVE_MAX_TU32S);
            stsCode = 4;
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tU32S[VarName]->ss.objectStatus)
            {
                rtdb_arr_tU32S[VarName]->tU32_val = NewVal;
                rtdb_arr_tU32S[VarName]->ss.signalState = SIGNAL_OK;
                rtdb_arr_tU32S[VarName]->ss.crc32 = rtdb_calcCrc32_tU32S(rtdb_arr_tU32S[VarName], sizeof(tU32S));
            }
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_write_tS8S( tS8SEnumT VarName , tS8 NewVal)
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TS8S, RTDB_ERR_SEMAPH_TAKE_TS8S);
    }
    else
    {
        // Request out of range TODO: add error reporting
        if (NUM_OF_tS8S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TS8S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tS8S(rtdb_arr_tS8S[VarName], sizeof(tS8S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TS8S, RTDB_ERR_WRONG_CRC_TS8S);
            stsCode = 2;
        }
        // check for MIN
        else if ( NewVal < rtdb_arr_tS8S[VarName]->tS8_min)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TS8S, RTDB_ERR_VAL_BELOW_MIN_TS8S);
            stsCode = 3;
        }
        // check for MAX
        else if ( NewVal > rtdb_arr_tS8S[VarName]->tS8_max)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TS8S, RTDB_ERR_VAL_ABOVE_MAX_TS8S);
            stsCode = 4;
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tS8S[VarName]->ss.objectStatus)
            {
                rtdb_arr_tS8S[VarName]->tS8_val = NewVal;
                rtdb_arr_tS8S[VarName]->ss.signalState = SIGNAL_OK;
                rtdb_arr_tS8S[VarName]->ss.crc32 = rtdb_calcCrc32_tS8S(rtdb_arr_tS8S[VarName], sizeof(tS8S));
            }
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_write_tS16S( tS16SEnumT VarName , tS16 NewVal)
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TS16S, RTDB_ERR_SEMAPH_TAKE_TS16S);
    }
    else
    {
        // Request out of range TODO: add error reporting
        if (NUM_OF_tS16S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TS16S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tS16S(rtdb_arr_tS16S[VarName], sizeof(tS16S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TS16S, RTDB_ERR_WRONG_CRC_TS16S);
            stsCode = 2;
        }
        // check for MIN
        else if ( NewVal < rtdb_arr_tS16S[VarName]->tS16_min)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TS16S, RTDB_ERR_VAL_BELOW_MIN_TS16S);
            stsCode = 3;
        }
        // check for MAX
        else if ( NewVal > rtdb_arr_tS16S[VarName]->tS16_max)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TS16S, RTDB_ERR_VAL_ABOVE_MAX_TS16S);
            stsCode = 4;
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tS16S[VarName]->ss.objectStatus)
            {
                rtdb_arr_tS16S[VarName]->tS16_val = NewVal;
                rtdb_arr_tS16S[VarName]->ss.signalState = SIGNAL_OK;
                rtdb_arr_tS16S[VarName]->ss.crc32 = rtdb_calcCrc32_tS16S(rtdb_arr_tS16S[VarName], sizeof(tS16S));
            }
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_write_tS32S( tS32SEnumT VarName , tS32 NewVal)
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TS32S, RTDB_ERR_SEMAPH_TAKE_TS32S);
    }
    else
    {
        // Request out of range TODO: add error reporting
        if (NUM_OF_tS32S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TS32S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tS32S(rtdb_arr_tS32S[VarName], sizeof(tS32S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TS32S, RTDB_ERR_WRONG_CRC_TS32S);
            stsCode = 2;
        }
        // check for MIN
        else if ( NewVal < rtdb_arr_tS32S[VarName]->tS32_min)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TS32S, RTDB_ERR_VAL_BELOW_MIN_TS32S);
            stsCode = 3;
        }
        // check for MAX
        else if ( NewVal > rtdb_arr_tS32S[VarName]->tS32_max)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TS32S, RTDB_ERR_VAL_ABOVE_MAX_TS32S);
            stsCode = 4;
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tS32S[VarName]->ss.objectStatus)
            {
                rtdb_arr_tS32S[VarName]->tS32_val = NewVal;
                rtdb_arr_tS32S[VarName]->ss.signalState = SIGNAL_OK;
                rtdb_arr_tS32S[VarName]->ss.crc32 = rtdb_calcCrc32_tS32S(rtdb_arr_tS32S[VarName], sizeof(tS32S));
            }
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_write_tES( tESEnumT VarName , tE NewVal)
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TES, RTDB_ERR_SEMAPH_TAKE_TES);
    }
    else
    {
        // Request out of range TODO: add error reporting
        if (NUM_OF_tES <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TES, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tES(rtdb_arr_tES[VarName], sizeof(tES)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TES, RTDB_ERR_WRONG_CRC_TES);
            stsCode = 2;
        }
        // check for MIN
        else if ( NewVal < rtdb_arr_tES[VarName]->tE_min)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TES, RTDB_ERR_VAL_BELOW_MIN_TES);
            stsCode = 3;
        }
        // check for MAX
        else if ( NewVal > rtdb_arr_tES[VarName]->tE_max)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TES, RTDB_ERR_VAL_ABOVE_MAX_TES);
            stsCode = 4;
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tES[VarName]->ss.objectStatus)
            {
                rtdb_arr_tES[VarName]->tE_val = NewVal;
                rtdb_arr_tES[VarName]->ss.signalState = SIGNAL_OK;
                rtdb_arr_tES[VarName]->ss.crc32 = rtdb_calcCrc32_tES(rtdb_arr_tES[VarName], sizeof(tES));
            }
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_write_tBS( tBSEnumT VarName , tB NewVal)
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TBS, RTDB_ERR_SEMAPH_TAKE_TBS);
    }
    else
    {
        // Request out of range TODO: add error reporting
        if (NUM_OF_tBS <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TBS, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tBS(rtdb_arr_tBS[VarName], sizeof(tBS)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TBS, RTDB_ERR_WRONG_CRC_TBS);
            stsCode = 2;
        }
        // check for MIN
        else if ( NewVal < rtdb_arr_tBS[VarName]->tB_min)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TBS, RTDB_ERR_VAL_BELOW_MIN_TBS);
            stsCode = 3;
        }
        // check for MAX
        else if ( NewVal > rtdb_arr_tBS[VarName]->tB_max)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TBS, RTDB_ERR_VAL_ABOVE_MAX_TBS);
            stsCode = 4;
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tBS[VarName]->ss.objectStatus)
            {
                rtdb_arr_tBS[VarName]->tB_val = NewVal;
                rtdb_arr_tBS[VarName]->ss.signalState = SIGNAL_OK;
                rtdb_arr_tBS[VarName]->ss.crc32 = rtdb_calcCrc32_tBS(rtdb_arr_tBS[VarName], sizeof(tBS));
            }
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_write_tF32S( tF32SEnumT VarName , tF32 NewVal)
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TF32S, RTDB_ERR_SEMAPH_TAKE_TF32S);
    }
    else
    {
        // Request out of range TODO: add error reporting
        if (NUM_OF_tF32S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TF32S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tF32S(rtdb_arr_tF32S[VarName], sizeof(tF32S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TF32S, RTDB_ERR_WRONG_CRC_TF32S);
            stsCode = 2;
        }
        // check for MIN
        else if ( NewVal < rtdb_arr_tF32S[VarName]->tF32_min)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TF32S, RTDB_ERR_VAL_BELOW_MIN_TF32S);
            stsCode = 3;
        }
        // check for MAX
        else if ( NewVal > rtdb_arr_tF32S[VarName]->tF32_max)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_WRITE_TF32S, RTDB_ERR_VAL_ABOVE_MAX_TF32S);
            stsCode = 4;
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tF32S[VarName]->ss.objectStatus)
            {
                rtdb_arr_tF32S[VarName]->tF32_val = NewVal;
                rtdb_arr_tF32S[VarName]->ss.signalState = SIGNAL_OK;
                rtdb_arr_tF32S[VarName]->ss.crc32 = rtdb_calcCrc32_tF32S(rtdb_arr_tF32S[VarName], sizeof(tF32S));
            }
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_overwrite_tU8S( tU8SEnumT VarName , tU8 NewVal )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TU8S, RTDB_ERR_SEMAPH_TAKE_TU8S);
    }
    else
    {
        // check CRC
        if (rtdb_checkCrc32_tU8S(rtdb_arr_tU8S[VarName], sizeof(tU8S))) // TODO
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TU8S, RTDB_ERR_WRONG_CRC_TU8S);
            stsCode = 1;
        }
        else
        {
            rtdb_arr_tU8S[VarName]->tU8_val = NewVal;
            rtdb_arr_tU8S[VarName]->ss.signalState = SIGNAL_OK;
            rtdb_arr_tU8S[VarName]->ss.objectStatus = OBJECT_OVERRIDDEN;
            rtdb_arr_tU8S[VarName]->ss.crc32 = rtdb_calcCrc32_tU8S(rtdb_arr_tU8S[VarName], sizeof(tU8S));
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_overwrite_tU16S( tU16SEnumT VarName , tU16 NewVal )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TU16S, RTDB_ERR_SEMAPH_TAKE_TU16S);
    }
    else
    {
        // check CRC
        if (rtdb_checkCrc32_tU16S(rtdb_arr_tU16S[VarName], sizeof(tU16S))) // TODO
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TU16S, RTDB_ERR_WRONG_CRC_TU16S);
            stsCode = 1;
        }
        else
        {
            rtdb_arr_tU16S[VarName]->tU16_val = NewVal;
            rtdb_arr_tU16S[VarName]->ss.signalState = SIGNAL_OK;
            rtdb_arr_tU16S[VarName]->ss.objectStatus = OBJECT_OVERRIDDEN;
            rtdb_arr_tU16S[VarName]->ss.crc32 = rtdb_calcCrc32_tU16S(rtdb_arr_tU16S[VarName], sizeof(tU16S));
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_overwrite_tU32S( tU32SEnumT VarName , tU32 NewVal )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TU32S, RTDB_ERR_SEMAPH_TAKE_TU32S);
    }
    else
    {
        // check CRC
        if (rtdb_checkCrc32_tU32S(rtdb_arr_tU32S[VarName], sizeof(tU32S))) // TODO
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TU32S, RTDB_ERR_WRONG_CRC_TU32S);
            stsCode = 1;
        }
        else
        {
            rtdb_arr_tU32S[VarName]->tU32_val = NewVal;
            rtdb_arr_tU32S[VarName]->ss.signalState = SIGNAL_OK;
            rtdb_arr_tU32S[VarName]->ss.objectStatus = OBJECT_OVERRIDDEN;
            rtdb_arr_tU32S[VarName]->ss.crc32 = rtdb_calcCrc32_tU32S(rtdb_arr_tU32S[VarName], sizeof(tU32S));
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_overwrite_tS8S( tS8SEnumT VarName , tS8 NewVal )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TS8S, RTDB_ERR_SEMAPH_TAKE_TS8S);
    }
    else
    {
        // check CRC
        if (rtdb_checkCrc32_tS8S(rtdb_arr_tS8S[VarName], sizeof(tS8S))) // TODO
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TS8S, RTDB_ERR_WRONG_CRC_TS8S);
            stsCode = 1;
        }
        else
        {
            rtdb_arr_tS8S[VarName]->tS8_val = NewVal;
            rtdb_arr_tS8S[VarName]->ss.signalState = SIGNAL_OK;
            rtdb_arr_tS8S[VarName]->ss.objectStatus = OBJECT_OVERRIDDEN;
            rtdb_arr_tS8S[VarName]->ss.crc32 = rtdb_calcCrc32_tS8S(rtdb_arr_tS8S[VarName], sizeof(tS8S));
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_overwrite_tS16S( tS16SEnumT VarName , tS16 NewVal )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TS16S, RTDB_ERR_SEMAPH_TAKE_TS16S);
    }
    else
    {
        // check CRC
        if (rtdb_checkCrc32_tS16S(rtdb_arr_tS16S[VarName], sizeof(tS16S))) // TODO
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TS16S, RTDB_ERR_WRONG_CRC_TS16S);
            stsCode = 1;
        }
        else
        {
            rtdb_arr_tS16S[VarName]->tS16_val = NewVal;
            rtdb_arr_tS16S[VarName]->ss.signalState = SIGNAL_OK;
            rtdb_arr_tS16S[VarName]->ss.objectStatus = OBJECT_OVERRIDDEN;
            rtdb_arr_tS16S[VarName]->ss.crc32 = rtdb_calcCrc32_tS16S(rtdb_arr_tS16S[VarName], sizeof(tS16S));
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_overwrite_tS32S( tS32SEnumT VarName , tS32 NewVal )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TS32S, RTDB_ERR_SEMAPH_TAKE_TS32S);
    }
    else
    {
        // check CRC
        if (rtdb_checkCrc32_tS32S(rtdb_arr_tS32S[VarName], sizeof(tS32S))) // TODO
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TS32S, RTDB_ERR_WRONG_CRC_TS32S);
            stsCode = 1;
        }
        else
        {
            rtdb_arr_tS32S[VarName]->tS32_val = NewVal;
            rtdb_arr_tS32S[VarName]->ss.signalState = SIGNAL_OK;
            rtdb_arr_tS32S[VarName]->ss.objectStatus = OBJECT_OVERRIDDEN;
            rtdb_arr_tS32S[VarName]->ss.crc32 = rtdb_calcCrc32_tS32S(rtdb_arr_tS32S[VarName], sizeof(tS32S));
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_overwrite_tES( tESEnumT VarName , tE NewVal )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TES, RTDB_ERR_SEMAPH_TAKE_TES);
    }
    else
    {
        // check CRC
        if (rtdb_checkCrc32_tES(rtdb_arr_tES[VarName], sizeof(tES))) // TODO
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TES, RTDB_ERR_WRONG_CRC_TES);
            stsCode = 1;
        }
        else
        {
            rtdb_arr_tES[VarName]->tE_val = NewVal;
            rtdb_arr_tES[VarName]->ss.signalState = SIGNAL_OK;
            rtdb_arr_tES[VarName]->ss.objectStatus = OBJECT_OVERRIDDEN;
            rtdb_arr_tES[VarName]->ss.crc32 = rtdb_calcCrc32_tES(rtdb_arr_tES[VarName], sizeof(tES));
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_overwrite_tBS( tBSEnumT VarName , tB NewVal )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TBS, RTDB_ERR_SEMAPH_TAKE_TBS);
    }
    else
    {
        // check CRC
        if (rtdb_checkCrc32_tBS(rtdb_arr_tBS[VarName], sizeof(tBS))) // TODO
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TBS, RTDB_ERR_WRONG_CRC_TBS);
            stsCode = 1;
        }
        else
        {
            rtdb_arr_tBS[VarName]->tB_val = NewVal;
            rtdb_arr_tBS[VarName]->ss.signalState = SIGNAL_OK;
            rtdb_arr_tBS[VarName]->ss.objectStatus = OBJECT_OVERRIDDEN;
            rtdb_arr_tBS[VarName]->ss.crc32 = rtdb_calcCrc32_tBS(rtdb_arr_tBS[VarName], sizeof(tBS));
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_overwrite_tF32S( tF32SEnumT VarName , tF32 NewVal )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TF32S, RTDB_ERR_SEMAPH_TAKE_TF32S);
    }
    else
    {
        // check CRC
        if (rtdb_checkCrc32_tF32S(rtdb_arr_tF32S[VarName], sizeof(tF32S))) // TODO
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_OVERWRITE_TF32S, RTDB_ERR_WRONG_CRC_TF32S);
            stsCode = 1;
        }
        else
        {
            rtdb_arr_tF32S[VarName]->tF32_val = NewVal;
            rtdb_arr_tF32S[VarName]->ss.signalState = SIGNAL_OK;
            rtdb_arr_tF32S[VarName]->ss.objectStatus = OBJECT_OVERRIDDEN;
            rtdb_arr_tF32S[VarName]->ss.crc32 = rtdb_calcCrc32_tF32S(rtdb_arr_tF32S[VarName], sizeof(tF32S));
        }
        rtdb_unlock();
    }
    return stsCode;
}

tU32 rtdb_releaseOverwrite_tU8S( tU8SEnumT VarName )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TU8S, RTDB_ERR_SEMAPH_TAKE_TU8S);
    }
    else
    {
        if (NUM_OF_tU8S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TU8S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tU8S(rtdb_arr_tU8S[VarName], sizeof(tU8S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TU8S, RTDB_ERR_WRONG_CRC_TU8S);
            stsCode = 2;
        }
        else
        {
            rtdb_arr_tU8S[VarName]->ss.objectStatus = OBJECT_STANDARD;
            rtdb_arr_tU8S[VarName]->ss.crc32 = rtdb_calcCrc32_tU8S(rtdb_arr_tU8S[VarName], sizeof(tU8S));
        }
        rtdb_unlock();
    }

    return stsCode;
}

tU32 rtdb_releaseOverwrite_tU16S( tU16SEnumT VarName )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TU16S, RTDB_ERR_SEMAPH_TAKE_TU16S);
    }
    else
    {
        if (NUM_OF_tU16S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TU16S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tU16S(rtdb_arr_tU16S[VarName], sizeof(tU16S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TU16S, RTDB_ERR_WRONG_CRC_TU16S);
            stsCode = 2;
        }
        else
        {
            rtdb_arr_tU16S[VarName]->ss.objectStatus = OBJECT_STANDARD;
            rtdb_arr_tU16S[VarName]->ss.crc32 = rtdb_calcCrc32_tU16S(rtdb_arr_tU16S[VarName], sizeof(tU16S));
        }
        rtdb_unlock();
    }

    return stsCode;
}

tU32 rtdb_releaseOverwrite_tU32S( tU32SEnumT VarName )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TU32S, RTDB_ERR_SEMAPH_TAKE_TU32S);
    }
    else
    {
        if (NUM_OF_tU32S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TU32S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tU32S(rtdb_arr_tU32S[VarName], sizeof(tU32S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TU32S, RTDB_ERR_WRONG_CRC_TU32S);
            stsCode = 2;
        }
        else
        {
            rtdb_arr_tU32S[VarName]->ss.objectStatus = OBJECT_STANDARD;
            rtdb_arr_tU32S[VarName]->ss.crc32 = rtdb_calcCrc32_tU32S(rtdb_arr_tU32S[VarName], sizeof(tU32S));
        }
        rtdb_unlock();
    }

    return stsCode;
}

tU32 rtdb_releaseOverwrite_tS8S( tS8SEnumT VarName )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TS8S, RTDB_ERR_SEMAPH_TAKE_TS8S);
    }
    else
    {
        if (NUM_OF_tS8S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TS8S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tS8S(rtdb_arr_tS8S[VarName], sizeof(tS8S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TS8S, RTDB_ERR_WRONG_CRC_TS8S);
            stsCode = 2;
        }
        else
        {
            rtdb_arr_tS8S[VarName]->ss.objectStatus = OBJECT_STANDARD;
            rtdb_arr_tS8S[VarName]->ss.crc32 = rtdb_calcCrc32_tS8S(rtdb_arr_tS8S[VarName], sizeof(tS8S));
        }
        rtdb_unlock();
    }

    return stsCode;
}

tU32 rtdb_releaseOverwrite_tS16S( tS16SEnumT VarName )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TS16S, RTDB_ERR_SEMAPH_TAKE_TS16S);
    }
    else
    {
        if (NUM_OF_tS16S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TS16S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tS16S(rtdb_arr_tS16S[VarName], sizeof(tS16S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TS16S, RTDB_ERR_WRONG_CRC_TS16S);
            stsCode = 2;
        }
        else
        {
            rtdb_arr_tS16S[VarName]->ss.objectStatus = OBJECT_STANDARD;
            rtdb_arr_tS16S[VarName]->ss.crc32 = rtdb_calcCrc32_tS16S(rtdb_arr_tS16S[VarName], sizeof(tS16S));
        }
        rtdb_unlock();
    }

    return stsCode;
}

tU32 rtdb_releaseOverwrite_tS32S( tS32SEnumT VarName )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TS32S, RTDB_ERR_SEMAPH_TAKE_TS32S);
    }
    else
    {
        if (NUM_OF_tS32S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TS32S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tS32S(rtdb_arr_tS32S[VarName], sizeof(tS32S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TS32S, RTDB_ERR_WRONG_CRC_TS32S);
            stsCode = 2;
        }
        else
        {
            rtdb_arr_tS32S[VarName]->ss.objectStatus = OBJECT_STANDARD;
            rtdb_arr_tS32S[VarName]->ss.crc32 = rtdb_calcCrc32_tS32S(rtdb_arr_tS32S[VarName], sizeof(tS32S));
        }
        rtdb_unlock();
    }

    return stsCode;
}

tU32 rtdb_releaseOverwrite_tES( tESEnumT VarName )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TES, RTDB_ERR_SEMAPH_TAKE_TES);
    }
    else
    {
        if (NUM_OF_tES <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TES, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tES(rtdb_arr_tES[VarName], sizeof(tES)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TES, RTDB_ERR_WRONG_CRC_TES);
            stsCode = 2;
        }
        else
        {
            rtdb_arr_tES[VarName]->ss.objectStatus = OBJECT_STANDARD;
            rtdb_arr_tES[VarName]->ss.crc32 = rtdb_calcCrc32_tES(rtdb_arr_tES[VarName], sizeof(tES));
        }
        rtdb_unlock();
    }

    return stsCode;
}

tU32 rtdb_releaseOverwrite_tBS( tBSEnumT VarName )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TBS, RTDB_ERR_SEMAPH_TAKE_TBS);
    }
    else
    {
        if (NUM_OF_tBS <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TBS, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tBS(rtdb_arr_tBS[VarName], sizeof(tBS)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TBS, RTDB_ERR_WRONG_CRC_TBS);
            stsCode = 2;
        }
        else
        {
            rtdb_arr_tBS[VarName]->ss.objectStatus = OBJECT_STANDARD;
            rtdb_arr_tBS[VarName]->ss.crc32 = rtdb_calcCrc32_tBS(rtdb_arr_tBS[VarName], sizeof(tBS));
        }
        rtdb_unlock();
    }

    return stsCode;
}

tU32 rtdb_releaseOverwrite_tF32S( tF32SEnumT VarName )
{
    tU32 stsCode = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TF32S, RTDB_ERR_SEMAPH_TAKE_TF32S);
    }
    else
    {
        if (NUM_OF_tF32S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TF32S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
            stsCode = 1;
        }
        // check CRC
        else if (rtdb_checkCrc32_tF32S(rtdb_arr_tF32S[VarName], sizeof(tF32S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_RELEASE_OVERWRITE_TF32S, RTDB_ERR_WRONG_CRC_TF32S);
            stsCode = 2;
        }
        else
        {
            rtdb_arr_tF32S[VarName]->ss.objectStatus = OBJECT_STANDARD;
            rtdb_arr_tF32S[VarName]->ss.crc32 = rtdb_calcCrc32_tF32S(rtdb_arr_tF32S[VarName], sizeof(tF32S));
        }
        rtdb_unlock();
    }

    return stsCode;
}

/**
* @brief Function returns current value of given variable
* @param tU8SEnumT VarName name of the variable as an enum
* @return Verified value of the given variable
*/
tU8 rtdb_read_tU8S( tU8SEnumT VarName )
{
    tU8 toReturn = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TU8S, RTDB_ERR_SEMAPH_TAKE_TU8S);
    }
    else
    {
        if (NUM_OF_tU8S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TU8S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // Check CRC
        else if (rtdb_checkCrc32_tU8S(rtdb_arr_tU8S[VarName], sizeof(tU8S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TU8S, RTDB_ERR_WRONG_CRC_TU8S);
        }
        else
        {
            toReturn = rtdb_arr_tU8S[VarName]->tU8_val;
        }
        rtdb_unlock();
    }
    return toReturn;
}

/**
* @brief Function returns current value of given variable
* @param tU16SEnumT VarName name of the variable as an enum
* @return Verified value of the given variable
*/
tU16 rtdb_read_tU16S( tU16SEnumT VarName )
{
    tU16 toReturn = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TU16S, RTDB_ERR_SEMAPH_TAKE_TU16S);
    }
    else
    {
        if (NUM_OF_tU16S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TU16S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // Check CRC
        else if (rtdb_checkCrc32_tU16S(rtdb_arr_tU16S[VarName], sizeof(tU16S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TU16S, RTDB_ERR_WRONG_CRC_TU16S);
        }
        else
        {
            toReturn = rtdb_arr_tU16S[VarName]->tU16_val;
        }
        rtdb_unlock();
    }
    return toReturn;
}

/**
* @brief Function returns current value of given variable
* @param tU32SEnumT VarName name of the variable as an enum
* @return Verified value of the given variable
*/
tU32 rtdb_read_tU32S( tU32SEnumT VarName )
{
    tU32 toReturn = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TU32S, RTDB_ERR_SEMAPH_TAKE_TU32S);
    }
    else
    {
        if (NUM_OF_tU32S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TU32S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // Check CRC
        else if (rtdb_checkCrc32_tU32S(rtdb_arr_tU32S[VarName], sizeof(tU32S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TU32S, RTDB_ERR_WRONG_CRC_TU32S);
        }
        else
        {
            toReturn = rtdb_arr_tU32S[VarName]->tU32_val;
        }
        rtdb_unlock();
    }
    return toReturn;
}

/**
* @brief Function returns current value of given variable
* @param tS8SEnumT VarName name of the variable as an enum
* @return Verified value of the given variable
*/
tS8 rtdb_read_tS8S( tS8SEnumT VarName )
{
    tS8 toReturn = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TS8S, RTDB_ERR_SEMAPH_TAKE_TS8S);
    }
    else
    {
        if (NUM_OF_tS8S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TS8S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // Check CRC
        else if (rtdb_checkCrc32_tS8S(rtdb_arr_tS8S[VarName], sizeof(tS8S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TS8S, RTDB_ERR_WRONG_CRC_TS8S);
        }
        else
        {
            toReturn = rtdb_arr_tS8S[VarName]->tS8_val;
        }
        rtdb_unlock();
    }
    return toReturn;
}

/**
* @brief Function returns current value of given variable
* @param tS16SEnumT VarName name of the variable as an enum
* @return Verified value of the given variable
*/
tS16 rtdb_read_tS16S( tS16SEnumT VarName )
{
    tS16 toReturn = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TS16S, RTDB_ERR_SEMAPH_TAKE_TS16S);
    }
    else
    {
        if (NUM_OF_tS16S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TS16S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // Check CRC
        else if (rtdb_checkCrc32_tS16S(rtdb_arr_tS16S[VarName], sizeof(tS16S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TS16S, RTDB_ERR_WRONG_CRC_TS16S);
        }
        else
        {
            toReturn = rtdb_arr_tS16S[VarName]->tS16_val;
        }
        rtdb_unlock();
    }
    return toReturn;
}

/**
* @brief Function returns current value of given variable
* @param tS32SEnumT VarName name of the variable as an enum
* @return Verified value of the given variable
*/
tS32 rtdb_read_tS32S( tS32SEnumT VarName )
{
    tS32 toReturn = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TS32S, RTDB_ERR_SEMAPH_TAKE_TS32S);
    }
    else
    {
        if (NUM_OF_tS32S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TS32S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // Check CRC
        else if (rtdb_checkCrc32_tS32S(rtdb_arr_tS32S[VarName], sizeof(tS32S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TS32S, RTDB_ERR_WRONG_CRC_TS32S);
        }
        else
        {
            toReturn = rtdb_arr_tS32S[VarName]->tS32_val;
        }
        rtdb_unlock();
    }
    return toReturn;
}

/**
* @brief Function returns current value of given variable
* @param tESEnumT VarName name of the variable as an enum
* @return Verified value of the given variable
*/
tE rtdb_read_tES( tESEnumT VarName )
{
    tE toReturn = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TES, RTDB_ERR_SEMAPH_TAKE_TES);
    }
    else
    {
        if (NUM_OF_tES <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TES, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // Check CRC
        else if (rtdb_checkCrc32_tES(rtdb_arr_tES[VarName], sizeof(tES)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TES, RTDB_ERR_WRONG_CRC_TES);
        }
        else
        {
            toReturn = rtdb_arr_tES[VarName]->tE_val;
        }
        rtdb_unlock();
    }
    return toReturn;
}

/**
* @brief Function returns current value of given variable
* @param tBSEnumT VarName name of the variable as an enum
* @return Verified value of the given variable
*/
tB rtdb_read_tBS( tBSEnumT VarName )
{
    tB toReturn = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TBS, RTDB_ERR_SEMAPH_TAKE_TBS);
    }
    else
    {
        if (NUM_OF_tBS <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TBS, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // Check CRC
        else if (rtdb_checkCrc32_tBS(rtdb_arr_tBS[VarName], sizeof(tBS)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TBS, RTDB_ERR_WRONG_CRC_TBS);
        }
        else
        {
            toReturn = rtdb_arr_tBS[VarName]->tB_val;
        }
        rtdb_unlock();
    }
    return toReturn;
}

/**
* @brief Function returns current value of given variable
* @param tF32SEnumT VarName name of the variable as an enum
* @return Verified value of the given variable
*/
tF32 rtdb_read_tF32S( tF32SEnumT VarName )
{
    tF32 toReturn = 0;
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TF32S, RTDB_ERR_SEMAPH_TAKE_TF32S);
    }
    else
    {
        if (NUM_OF_tF32S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TF32S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // Check CRC
        else if (rtdb_checkCrc32_tF32S(rtdb_arr_tF32S[VarName], sizeof(tF32S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_READ_TF32S, RTDB_ERR_WRONG_CRC_TF32S);
        }
        else
        {
            toReturn = rtdb_arr_tF32S[VarName]->tF32_val;
        }
        rtdb_unlock();
    }
    return toReturn;
}
void rtdb_setSS_tU8S( tU8SEnumT VarName , signalStateT newSS)
{
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TU8S, RTDB_ERR_SEMAPH_TAKE_TU8S);
    }
    else
    {
        if (NUM_OF_tU8S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TU8S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // check CRC
        else if (rtdb_checkCrc32_tU8S(rtdb_arr_tU8S[VarName], sizeof(tU8S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TU8S, RTDB_ERR_WRONG_CRC_TU8S);
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tU8S[VarName]->ss.objectStatus)
            {
                rtdb_arr_tU8S[VarName]->ss.signalState = newSS;
                rtdb_arr_tU8S[VarName]->ss.crc32 = rtdb_calcCrc32_tU8S(rtdb_arr_tU8S[VarName], sizeof(tU8S));
            }
        }
        rtdb_unlock();
    }
}

void rtdb_setSS_tU16S( tU16SEnumT VarName , signalStateT newSS)
{
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TU16S, RTDB_ERR_SEMAPH_TAKE_TU16S);
    }
    else
    {
        if (NUM_OF_tU16S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TU16S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // check CRC
        else if (rtdb_checkCrc32_tU16S(rtdb_arr_tU16S[VarName], sizeof(tU16S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TU16S, RTDB_ERR_WRONG_CRC_TU16S);
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tU16S[VarName]->ss.objectStatus)
            {
                rtdb_arr_tU16S[VarName]->ss.signalState = newSS;
                rtdb_arr_tU16S[VarName]->ss.crc32 = rtdb_calcCrc32_tU16S(rtdb_arr_tU16S[VarName], sizeof(tU16S));
            }
        }
        rtdb_unlock();
    }
}

void rtdb_setSS_tU32S( tU32SEnumT VarName , signalStateT newSS)
{
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TU32S, RTDB_ERR_SEMAPH_TAKE_TU32S);
    }
    else
    {
        if (NUM_OF_tU32S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TU32S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // check CRC
        else if (rtdb_checkCrc32_tU32S(rtdb_arr_tU32S[VarName], sizeof(tU32S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TU32S, RTDB_ERR_WRONG_CRC_TU32S);
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tU32S[VarName]->ss.objectStatus)
            {
                rtdb_arr_tU32S[VarName]->ss.signalState = newSS;
                rtdb_arr_tU32S[VarName]->ss.crc32 = rtdb_calcCrc32_tU32S(rtdb_arr_tU32S[VarName], sizeof(tU32S));
            }
        }
        rtdb_unlock();
    }
}

void rtdb_setSS_tS8S( tS8SEnumT VarName , signalStateT newSS)
{
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TS8S, RTDB_ERR_SEMAPH_TAKE_TS8S);
    }
    else
    {
        if (NUM_OF_tS8S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TS8S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // check CRC
        else if (rtdb_checkCrc32_tS8S(rtdb_arr_tS8S[VarName], sizeof(tS8S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TS8S, RTDB_ERR_WRONG_CRC_TS8S);
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tS8S[VarName]->ss.objectStatus)
            {
                rtdb_arr_tS8S[VarName]->ss.signalState = newSS;
                rtdb_arr_tS8S[VarName]->ss.crc32 = rtdb_calcCrc32_tS8S(rtdb_arr_tS8S[VarName], sizeof(tS8S));
            }
        }
        rtdb_unlock();
    }
}

void rtdb_setSS_tS16S( tS16SEnumT VarName , signalStateT newSS)
{
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TS16S, RTDB_ERR_SEMAPH_TAKE_TS16S);
    }
    else
    {
        if (NUM_OF_tS16S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TS16S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // check CRC
        else if (rtdb_checkCrc32_tS16S(rtdb_arr_tS16S[VarName], sizeof(tS16S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TS16S, RTDB_ERR_WRONG_CRC_TS16S);
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tS16S[VarName]->ss.objectStatus)
            {
                rtdb_arr_tS16S[VarName]->ss.signalState = newSS;
                rtdb_arr_tS16S[VarName]->ss.crc32 = rtdb_calcCrc32_tS16S(rtdb_arr_tS16S[VarName], sizeof(tS16S));
            }
        }
        rtdb_unlock();
    }
}

void rtdb_setSS_tS32S( tS32SEnumT VarName , signalStateT newSS)
{
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TS32S, RTDB_ERR_SEMAPH_TAKE_TS32S);
    }
    else
    {
        if (NUM_OF_tS32S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TS32S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // check CRC
        else if (rtdb_checkCrc32_tS32S(rtdb_arr_tS32S[VarName], sizeof(tS32S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TS32S, RTDB_ERR_WRONG_CRC_TS32S);
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tS32S[VarName]->ss.objectStatus)
            {
                rtdb_arr_tS32S[VarName]->ss.signalState = newSS;
                rtdb_arr_tS32S[VarName]->ss.crc32 = rtdb_calcCrc32_tS32S(rtdb_arr_tS32S[VarName], sizeof(tS32S));
            }
        }
        rtdb_unlock();
    }
}

void rtdb_setSS_tES( tESEnumT VarName , signalStateT newSS)
{
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TES, RTDB_ERR_SEMAPH_TAKE_TES);
    }
    else
    {
        if (NUM_OF_tES <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TES, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // check CRC
        else if (rtdb_checkCrc32_tES(rtdb_arr_tES[VarName], sizeof(tES)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TES, RTDB_ERR_WRONG_CRC_TES);
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tES[VarName]->ss.objectStatus)
            {
                rtdb_arr_tES[VarName]->ss.signalState = newSS;
                rtdb_arr_tES[VarName]->ss.crc32 = rtdb_calcCrc32_tES(rtdb_arr_tES[VarName], sizeof(tES));
            }
        }
        rtdb_unlock();
    }
}

void rtdb_setSS_tBS( tBSEnumT VarName , signalStateT newSS)
{
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TBS, RTDB_ERR_SEMAPH_TAKE_TBS);
    }
    else
    {
        if (NUM_OF_tBS <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TBS, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // check CRC
        else if (rtdb_checkCrc32_tBS(rtdb_arr_tBS[VarName], sizeof(tBS)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TBS, RTDB_ERR_WRONG_CRC_TBS);
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tBS[VarName]->ss.objectStatus)
            {
                rtdb_arr_tBS[VarName]->ss.signalState = newSS;
                rtdb_arr_tBS[VarName]->ss.crc32 = rtdb_calcCrc32_tBS(rtdb_arr_tBS[VarName], sizeof(tBS));
            }
        }
        rtdb_unlock();
    }
}

void rtdb_setSS_tF32S( tF32SEnumT VarName , signalStateT newSS)
{
    if (!rtdb_lock())
    {
        errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TF32S, RTDB_ERR_SEMAPH_TAKE_TF32S);
    }
    else
    {
        if (NUM_OF_tF32S <= VarName)
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TF32S, ERRH_ERR_READ_INDEX_OUT_OF_BOUNDS_U32);
        }
        // check CRC
        else if (rtdb_checkCrc32_tF32S(rtdb_arr_tF32S[VarName], sizeof(tF32S)))
        {
            errh_reportError(ERRH_WARNING, MODULE_RTDB, VarName, RTDB_API_SETSS_TF32S, RTDB_ERR_WRONG_CRC_TF32S);
        }
        else
        {
            if (OBJECT_STANDARD == rtdb_arr_tF32S[VarName]->ss.objectStatus)
            {
                rtdb_arr_tF32S[VarName]->ss.signalState = newSS;
                rtdb_arr_tF32S[VarName]->ss.crc32 = rtdb_calcCrc32_tF32S(rtdb_arr_tF32S[VarName], sizeof(tF32S));
            }
        }
        rtdb_unlock();
    }
}


void rtdb_init(tRTDB_INITDATA_STR* RtdbCfg)
{
    if (true == rtdb_s_moduleInit_tB)
    {
        errh_reportError(ERRH_NOTIF, MODULE_RTDB, 0, RTDB_API_INIT_U32, ERRH_MODULE_ALREADY_INIT);
    }
    else if (NULL == RtdbCfg)
    {
        errh_reportError(ERRH_ERROR_CRITICAL, MODULE_RTDB, 0, RTDB_API_INIT_U32, ERRH_POINTER_IS_NULL);
    }
    else
    {
        db_mutex = xSemaphoreCreateMutex();
        trgd_rtdb_init();
        rtdb_s_moduleInit_tB = true;
    }
}
