/*
 * This file was autogenerated by RTDB Generator script
 * Date of generation: 24 May 2025 at 09:46:05
 * To modify this file run the RTDB Generator script again
 * Include this header file only in the corresponding module .cpp file to avoid multiple definitions
 */

#ifndef RTDB_H
#define RTDB_H

#include "rtdb_vars.h"
#include "errh.h"

#define RTDB_API_INIT_U32                         ((uint32_t) 1)
#define RTDB_API_WRITE_TU8S                       ((uint32_t) 2)
#define RTDB_API_WRITE_TU16S                      ((uint32_t) 3)
#define RTDB_API_WRITE_TU32S                      ((uint32_t) 4)
#define RTDB_API_WRITE_TS8S                       ((uint32_t) 5)
#define RTDB_API_WRITE_TS16S                      ((uint32_t) 6)
#define RTDB_API_WRITE_TS32S                      ((uint32_t) 7)
#define RTDB_API_WRITE_TES                        ((uint32_t) 8)
#define RTDB_API_WRITE_TBS                        ((uint32_t) 9)
#define RTDB_API_WRITE_TF32S                      ((uint32_t) 10)
#define RTDB_API_READ_TU8S                        ((uint32_t) 11)
#define RTDB_API_READ_TU16S                       ((uint32_t) 12)
#define RTDB_API_READ_TU32S                       ((uint32_t) 13)
#define RTDB_API_READ_TS8S                        ((uint32_t) 14)
#define RTDB_API_READ_TS16S                       ((uint32_t) 15)
#define RTDB_API_READ_TS32S                       ((uint32_t) 16)
#define RTDB_API_READ_TES                         ((uint32_t) 17)
#define RTDB_API_READ_TBS                         ((uint32_t) 18)
#define RTDB_API_READ_TF32S                       ((uint32_t) 19)
#define RTDB_API_OVERWRITE_TU8S                   ((uint32_t) 20)
#define RTDB_API_OVERWRITE_TU16S                  ((uint32_t) 21)
#define RTDB_API_OVERWRITE_TU32S                  ((uint32_t) 22)
#define RTDB_API_OVERWRITE_TS8S                   ((uint32_t) 23)
#define RTDB_API_OVERWRITE_TS16S                  ((uint32_t) 24)
#define RTDB_API_OVERWRITE_TS32S                  ((uint32_t) 25)
#define RTDB_API_OVERWRITE_TES                    ((uint32_t) 26)
#define RTDB_API_OVERWRITE_TBS                    ((uint32_t) 27)
#define RTDB_API_OVERWRITE_TF32S                  ((uint32_t) 28)
#define RTDB_API_RELEASE_OVERWRITE_TU8S           ((uint32_t) 29)
#define RTDB_API_RELEASE_OVERWRITE_TU16S          ((uint32_t) 30)
#define RTDB_API_RELEASE_OVERWRITE_TU32S          ((uint32_t) 31)
#define RTDB_API_RELEASE_OVERWRITE_TS8S           ((uint32_t) 32)
#define RTDB_API_RELEASE_OVERWRITE_TS16S          ((uint32_t) 33)
#define RTDB_API_RELEASE_OVERWRITE_TS32S          ((uint32_t) 34)
#define RTDB_API_RELEASE_OVERWRITE_TES            ((uint32_t) 35)
#define RTDB_API_RELEASE_OVERWRITE_TBS            ((uint32_t) 36)
#define RTDB_API_RELEASE_OVERWRITE_TF32S          ((uint32_t) 37)
#define RTDB_API_CALC_CRC_TU8S                    ((uint32_t) 38)
#define RTDB_API_CALC_CRC_TU16S                   ((uint32_t) 39)
#define RTDB_API_CALC_CRC_TU32S                   ((uint32_t) 40)
#define RTDB_API_CALC_CRC_TS8S                    ((uint32_t) 41)
#define RTDB_API_CALC_CRC_TS16S                   ((uint32_t) 42)
#define RTDB_API_CALC_CRC_TS32S                   ((uint32_t) 43)
#define RTDB_API_CALC_CRC_TES                     ((uint32_t) 44)
#define RTDB_API_CALC_CRC_TBS                     ((uint32_t) 45)
#define RTDB_API_CALC_CRC_TF32S                   ((uint32_t) 46)
#define RTDB_API_SETSS_TU8S                       ((uint32_t) 47)
#define RTDB_API_SETSS_TU16S                      ((uint32_t) 48)
#define RTDB_API_SETSS_TU32S                      ((uint32_t) 49)
#define RTDB_API_SETSS_TS8S                       ((uint32_t) 50)
#define RTDB_API_SETSS_TS16S                      ((uint32_t) 51)
#define RTDB_API_SETSS_TS32S                      ((uint32_t) 52)
#define RTDB_API_SETSS_TES                        ((uint32_t) 53)
#define RTDB_API_SETSS_TBS                        ((uint32_t) 54)
#define RTDB_API_SETSS_TF32S                      ((uint32_t) 55)

#define RTDB_ERR_WRONG_CRC_TU8S                   ((uint32_t) 1)
#define RTDB_ERR_WRONG_CRC_TU16S                  ((uint32_t) 2)
#define RTDB_ERR_WRONG_CRC_TU32S                  ((uint32_t) 3)
#define RTDB_ERR_WRONG_CRC_TS8S                   ((uint32_t) 4)
#define RTDB_ERR_WRONG_CRC_TS16S                  ((uint32_t) 5)
#define RTDB_ERR_WRONG_CRC_TS32S                  ((uint32_t) 6)
#define RTDB_ERR_WRONG_CRC_TES                    ((uint32_t) 7)
#define RTDB_ERR_WRONG_CRC_TBS                    ((uint32_t) 8)
#define RTDB_ERR_WRONG_CRC_TF32S                  ((uint32_t) 9)
#define RTDB_ERR_VAL_BELOW_MIN_TU8S               ((uint32_t) 10)
#define RTDB_ERR_VAL_BELOW_MIN_TU16S              ((uint32_t) 11)
#define RTDB_ERR_VAL_BELOW_MIN_TU32S              ((uint32_t) 12)
#define RTDB_ERR_VAL_BELOW_MIN_TS8S               ((uint32_t) 13)
#define RTDB_ERR_VAL_BELOW_MIN_TS16S              ((uint32_t) 14)
#define RTDB_ERR_VAL_BELOW_MIN_TS32S              ((uint32_t) 15)
#define RTDB_ERR_VAL_BELOW_MIN_TES                ((uint32_t) 16)
#define RTDB_ERR_VAL_BELOW_MIN_TBS                ((uint32_t) 17)
#define RTDB_ERR_VAL_BELOW_MIN_TF32S              ((uint32_t) 18)
#define RTDB_ERR_VAL_ABOVE_MAX_TU8S               ((uint32_t) 19)
#define RTDB_ERR_VAL_ABOVE_MAX_TU16S              ((uint32_t) 20)
#define RTDB_ERR_VAL_ABOVE_MAX_TU32S              ((uint32_t) 21)
#define RTDB_ERR_VAL_ABOVE_MAX_TS8S               ((uint32_t) 22)
#define RTDB_ERR_VAL_ABOVE_MAX_TS16S              ((uint32_t) 23)
#define RTDB_ERR_VAL_ABOVE_MAX_TS32S              ((uint32_t) 24)
#define RTDB_ERR_VAL_ABOVE_MAX_TES                ((uint32_t) 25)
#define RTDB_ERR_VAL_ABOVE_MAX_TBS                ((uint32_t) 26)
#define RTDB_ERR_VAL_ABOVE_MAX_TF32S              ((uint32_t) 27)
#define RTDB_ERR_SEMAPH_TAKE_TU8S                 ((uint32_t) 28)
#define RTDB_ERR_SEMAPH_TAKE_TU16S                ((uint32_t) 29)
#define RTDB_ERR_SEMAPH_TAKE_TU32S                ((uint32_t) 30)
#define RTDB_ERR_SEMAPH_TAKE_TS8S                 ((uint32_t) 31)
#define RTDB_ERR_SEMAPH_TAKE_TS16S                ((uint32_t) 32)
#define RTDB_ERR_SEMAPH_TAKE_TS32S                ((uint32_t) 33)
#define RTDB_ERR_SEMAPH_TAKE_TES                  ((uint32_t) 34)
#define RTDB_ERR_SEMAPH_TAKE_TBS                  ((uint32_t) 35)
#define RTDB_ERR_SEMAPH_TAKE_TF32S                ((uint32_t) 36)


typedef struct
{
} tRTDB_INITDATA_STR;

// ASSIGN DURING INIT
void rtdb_assign_tU8S ( tU8S* VarAddrs, tU32 Indx, unitEnumT Unit, tU8 Min, tU8 Def, tU8 Max, const char* Comment );
void rtdb_assign_tU16S( tU16S* VarAddrs, tU32 Indx, unitEnumT Unit, tU16 Min, tU16 Def, tU16 Max, const char* Comment );
void rtdb_assign_tU32S( tU32S* VarAddrs, tU32 Indx, unitEnumT Unit, tU32 Min, tU32 Def, tU32 Max, const char* Comment );

void rtdb_assign_tS8S ( tS8S* VarAddrs, tU32 Indx, unitEnumT Unit, tS8 Min, tS8 Def, tS8 Max, const char* Comment );
void rtdb_assign_tS16S( tS16S* VarAddrs, tU32 Indx, unitEnumT Unit, tS16 Min, tS16 Def, tS16 Max, const char* Comment );
void rtdb_assign_tS32S( tS32S* VarAddrs, tU32 Indx, unitEnumT Unit, tS32 Min, tS32 Def, tS32 Max, const char* Comment );

void rtdb_assign_tES   ( tES*  VarAddrs, tU32 Indx, unitEnumT Unit, tU32 Min, tU32 Def, tU32 Max, const char* Comment );
void rtdb_assign_tBS   ( tBS*  VarAddrs, tU32 Indx, unitEnumT Unit, tU8 Min, tU8 Def, tU8 Max, const char* Comment );
void rtdb_assign_tF32S ( tF32S* VarAddrs, tU32 Indx, unitEnumT Unit, float Min, float Def, float Max, const char* Comment );


// WRITE DURING RUNTIME
tU32 rtdb_write_tU8S ( tU8SEnumT VarName, tU8 NewVal );
tU32 rtdb_write_tU16S( tU16SEnumT VarName, tU16 NewVal );
tU32 rtdb_write_tU32S( tU32SEnumT VarName, tU32 NewVal );

tU32 rtdb_write_tS8S ( tS8SEnumT VarName, tS8 NewVal );
tU32 rtdb_write_tS16S( tS16SEnumT VarName, tS16 NewVal );
tU32 rtdb_write_tS32S( tS32SEnumT VarName, tS32 NewVal );

tU32 rtdb_write_tES   ( tESEnumT  VarName, tE NewVal );
tU32 rtdb_write_tBS   ( tBSEnumT  VarName, tB NewVal );
tU32 rtdb_write_tF32S ( tF32SEnumT VarName, float NewVal );

// OVERWRITE DURING RUNTIME
tU32 rtdb_overwrite_tU8S ( tU8SEnumT VarName, tU8 NewVal );
tU32 rtdb_overwrite_tU16S( tU16SEnumT VarName, tU16 NewVal );
tU32 rtdb_overwrite_tU32S( tU32SEnumT VarName, tU32 NewVal );

tU32 rtdb_overwrite_tS8S ( tS8SEnumT VarName, tS8 NewVal );
tU32 rtdb_overwrite_tS16S( tS16SEnumT VarName, tS16 NewVal );
tU32 rtdb_overwrite_tS32S( tS32SEnumT VarName, tS32 NewVal );

tU32 rtdb_overwrite_tES   ( tESEnumT  VarName, tE NewVal );
tU32 rtdb_overwrite_tBS   ( tBSEnumT  VarName, tB NewVal );
tU32 rtdb_overwrite_tF32S ( tF32SEnumT VarName, float NewVal );


// RELEASE OVERWRITE CONTROL
tU32 rtdb_releaseOverwrite_tU8S ( tU8SEnumT VarName );
tU32 rtdb_releaseOverwrite_tU16S( tU16SEnumT VarName );
tU32 rtdb_releaseOverwrite_tU32S( tU32SEnumT VarName );

tU32 rtdb_releaseOverwrite_tS8S ( tS8SEnumT VarName );
tU32 rtdb_releaseOverwrite_tS16S( tS16SEnumT VarName );
tU32 rtdb_releaseOverwrite_tS32S( tS32SEnumT VarName );

tU32 rtdb_releaseOverwrite_tES   ( tESEnumT  VarName );
tU32 rtdb_releaseOverwrite_tBS   ( tBSEnumT  VarName );
tU32 rtdb_releaseOverwrite_tF32S ( tF32SEnumT VarName );

// READ DURING RUNTIME
tU8  rtdb_read_tU8S ( tU8SEnumT VarName );
tU16 rtdb_read_tU16S( tU16SEnumT VarName );
tU32 rtdb_read_tU32S( tU32SEnumT VarName );

tS8  rtdb_read_tS8S ( tS8SEnumT VarName );
tS16 rtdb_read_tS16S( tS16SEnumT VarName );
tS32 rtdb_read_tS32S( tS32SEnumT VarName );

tE    rtdb_read_tES   ( tESEnumT  VarName );
tB    rtdb_read_tBS   ( tBSEnumT  VarName );
tF32  rtdb_read_tF32S ( tF32SEnumT VarName );


// AUXILLIARY FUNCTIONS

tU32 rtdb_checkCrc32_tU8S(tU8S* VarAddrs, tU32 VarSize);
tU32 rtdb_calcCrc32_tU8S(tU8S* VarAddrs, tU32 VarSize);

void rtdb_setSS_tU8S( tU8SEnumT VarName , signalStateT newSS);

tU32 rtdb_checkCrc32_tU16S(tU16S* VarAddrs, tU32 VarSize);
tU32 rtdb_calcCrc32_tU16S(tU16S* VarAddrs, tU32 VarSize);

void rtdb_setSS_tU16S( tU16SEnumT VarName , signalStateT newSS);

tU32 rtdb_checkCrc32_tU32S(tU32S* VarAddrs, tU32 VarSize);
tU32 rtdb_calcCrc32_tU32S(tU32S* VarAddrs, tU32 VarSize);

void rtdb_setSS_tU32S( tU32SEnumT VarName , signalStateT newSS);

tU32 rtdb_checkCrc32_tS8S(tS8S* VarAddrs, tU32 VarSize);
tU32 rtdb_calcCrc32_tS8S(tS8S* VarAddrs, tU32 VarSize);

void rtdb_setSS_tS8S( tS8SEnumT VarName , signalStateT newSS);

tU32 rtdb_checkCrc32_tS16S(tS16S* VarAddrs, tU32 VarSize);
tU32 rtdb_calcCrc32_tS16S(tS16S* VarAddrs, tU32 VarSize);

void rtdb_setSS_tS16S( tS16SEnumT VarName , signalStateT newSS);

tU32 rtdb_checkCrc32_tS32S(tS32S* VarAddrs, tU32 VarSize);
tU32 rtdb_calcCrc32_tS32S(tS32S* VarAddrs, tU32 VarSize);

void rtdb_setSS_tS32S( tS32SEnumT VarName , signalStateT newSS);

tU32 rtdb_checkCrc32_tES(tES* VarAddrs, tU32 VarSize);
tU32 rtdb_calcCrc32_tES(tES* VarAddrs, tU32 VarSize);

void rtdb_setSS_tES( tESEnumT VarName , signalStateT newSS);

tU32 rtdb_checkCrc32_tBS(tBS* VarAddrs, tU32 VarSize);
tU32 rtdb_calcCrc32_tBS(tBS* VarAddrs, tU32 VarSize);

void rtdb_setSS_tBS( tBSEnumT VarName , signalStateT newSS);

tU32 rtdb_checkCrc32_tF32S(tF32S* VarAddrs, tU32 VarSize);
tU32 rtdb_calcCrc32_tF32S(tF32S* VarAddrs, tU32 VarSize);

void rtdb_setSS_tF32S( tF32SEnumT VarName , signalStateT newSS);

void trgd_rtdb_init(void);
void rtdb_init(tRTDB_INITDATA_STR* RtdbCfg);

#endif
