/*
 * This file was autogenerated by RTDB Generator script
 * Date of generation: 24 May 2025 at 09:46:05
 * To modify this file run the RTDB Generator script again
 * Include this header file only in the corresponding module .cpp file to avoid multiple definitions
 */

#ifndef RTDB_VARS_H
#define RTDB_VARS_H

#include<limits.h>
#include<stdint.h>
#include<float.h>

#include<vars.h>

// Variable units lookup table and enum
typedef enum
{
    VAR_UNIT_us = 0,
    VAR_UNIT_MAX_NUM
} unitEnumT;

// tU8S
typedef enum
{
    NUM_OF_tU8S = 0
} tU8SEnumT;

// tU16S
typedef enum
{
    NUM_OF_tU16S = 0
} tU16SEnumT;

// tU32S
typedef enum
{
    TRGD_TI_US_ZEROCROSSTRIGGERDELAY_U32 = 0,     // Time in us between zero-crossing detection and its actual occurrence.
    NUM_OF_tU32S = 1
} tU32SEnumT;

// tS8S
typedef enum
{
    NUM_OF_tS8S = 0
} tS8SEnumT;

// tS16S
typedef enum
{
    NUM_OF_tS16S = 0
} tS16SEnumT;

// tS32S
typedef enum
{
    NUM_OF_tS32S = 0
} tS32SEnumT;

// tES
typedef enum
{
    NUM_OF_tES = 0
} tESEnumT;

// tBS
typedef enum
{
    NUM_OF_tBS = 0
} tBSEnumT;

// tF32S
typedef enum
{
    NUM_OF_tF32S = 0
} tF32SEnumT;

typedef enum
{
    SIGNAL_ERROR = 0x00,         ///< Value unreliable
    SIGNAL_MISSING = 0x0F,       ///< Value missing
    SIGNAL_CAN_TIMEOUT = 0x3F,   ///< Timeout on CAN signal
    SIGNAL_OK = 0xFF             ///< Value reliable, use value
} signalStateT;

typedef enum
{
    OBJECT_STANDARD = 0,    ///< Value is derived from program
    OBJECT_OVERRIDDEN = 1,  ///< Value is derived from external source
    OBJECT_NOT_INIT = 255,
} objectStatusT;

typedef struct
{
    tU32 crc32;                         ///< CRC of all object's variables
    signalStateT signalState : 8;       ///< state of the signal, i.e., its reliability
    objectStatusT objectStatus : 8;     ///< status of this object
    tU8 signalUnit;                     ///< unit of the signal, i.e., volt or RPM
    const char* signalCmnt;             ///< Signal comment
} rtdbT;

typedef struct
{
    rtdbT ss;
    tS8 tS8_val;
    tS8 tS8_min;
    tS8 tS8_def;
    tS8 tS8_max;
} tS8S;

typedef struct
{
    rtdbT ss;
    tS16 tS16_val;
    tS16 tS16_min;
    tS16 tS16_def;
    tS16 tS16_max;
} tS16S;

typedef struct
{
    rtdbT ss;
    tS32 tS32_val;
    tS32 tS32_min;
    tS32 tS32_def;
    tS32 tS32_max;
} tS32S;

typedef struct
{
    rtdbT ss;
    tU8 tU8_val;
    tU8 tU8_min;
    tU8 tU8_def;
    tU8 tU8_max;
} tU8S;

typedef struct
{
    rtdbT ss;
    tU16 tU16_val;
    tU16 tU16_min;
    tU16 tU16_def;
    tU16 tU16_max;
} tU16S;

typedef struct
{
    rtdbT ss;
    tU32 tU32_val;
    tU32 tU32_min;
    tU32 tU32_def;
    tU32 tU32_max;
} tU32S;

typedef struct
{
    rtdbT ss;
    tF32 tF32_val;
    tF32 tF32_min;
    tF32 tF32_def;
    tF32 tF32_max;
} tF32S;

typedef struct
{
    rtdbT ss;
    tU8 tB_val;
    tU8 tB_min;
    tU8 tB_def;
    tU8 tB_max;
} tBS;

typedef struct
{
    rtdbT ss;
    tU32 tE_val;
    tU32 tE_min;
    tU32 tE_def;
    tU32 tE_max;
} tES;

#endif
