/*
 * This file was autogenerated by RTDB Generator script
 * Date of generation: 24 May 2025 at 09:46:05
 * To modify this file run the RTDB Generator script again
 * Include this header file only in the corresponding module .cpp file to avoid multiple definitions
 */

#ifndef TRGD_RTDB_H
#define TRGD_RTDB_H

#include "rtdb.h"
#include "trgd_rtdb_vars.h"

void trgd_rtdb_init()
{
    rtdb_assign_tU32S(&trgd_ti_us_zeroCrossTriggerDelay_U32, TRGD_TI_US_ZEROCROSSTRIGGERDELAY_U32, VAR_UNIT_us, 0, 580, 1000, "Time in us between zero-crossing detection and its actual occurrence.");
}
#endif
